# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-21 09:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u5206\u7c7b',
                'verbose_name_plural': '\u535a\u5ba2\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('img', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='\u535a\u5ba2\u914d\u56fe')),
                ('body', models.TextField(verbose_name='\u6b63\u6587')),
                ('abstract', models.TextField(blank=True, max_length=256, null=True, verbose_name='\u6458\u8981')),
                ('visiting', models.PositiveIntegerField(default=0, verbose_name='\u8bbf\u95ee\u91cf')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('modifyed_time', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
                ('category', models.ManyToManyField(to='blog.Category', verbose_name='\u535a\u5ba2\u5206\u7c7b')),
            ],
            options={
                'ordering': ['-created_time'],
                'verbose_name': '\u535a\u5ba2\u6b63\u6587',
                'verbose_name_plural': '\u535a\u5ba2\u6b63\u6587',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='\u6807\u7b7e')),
            ],
            options={
                'verbose_name': '\u535a\u5ba2\u6807\u7b7e',
                'verbose_name_plural': '\u535a\u5ba2\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
